# Generated by Django 2.1.1 on 2018-10-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipfDistribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorterIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contents', models.ManyToManyField(to='zipfDistribution.Content')),
            ],
        ),
        migrations.CreateModel(
            name='RawIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contents', models.ManyToManyField(to='zipfDistribution.Content')),
            ],
        ),
    ]
